import type { Opportunity, OpportunityType, StudentProfile } from "./types";

export const OPPORTUNITY_TYPES: OpportunityType[] = [
  "Hackathon",
  "Workshop",
  "Competition",
  "Internship",
  "Seminar",
  "Bootcamp",
];

export const CAREER_GOALS = [
  "Machine Learning Engineer",
  "Full Stack Developer",
  "Data Analyst",
  "Cybersecurity Analyst",
  "Product Designer",
  "Cloud / DevOps Engineer",
];

/**
 * Skills that matter for each career track, with the proficiency (0-100)
 * a student is expected to reach before being job ready.
 */
export const CAREER_SKILL_MAP: Record<string, Record<string, number>> = {
  "Machine Learning Engineer": {
    Python: 85,
    "Machine Learning": 85,
    Statistics: 75,
    "Deep Learning": 70,
    SQL: 60,
    DSA: 70,
  },
  "Full Stack Developer": {
    JavaScript: 85,
    React: 80,
    "Node.js": 75,
    SQL: 65,
    DSA: 65,
    "UI/UX": 55,
  },
  "Data Analyst": {
    SQL: 85,
    Python: 70,
    Statistics: 80,
    "Data Visualization": 75,
    Excel: 60,
  },
  "Cybersecurity Analyst": {
    Networking: 80,
    Linux: 75,
    Cryptography: 65,
    Python: 60,
    "Cloud Security": 60,
  },
  "Product Designer": {
    "UI/UX": 90,
    Figma: 85,
    "Design Systems": 70,
    "User Research": 70,
    "Web Development": 45,
  },
  "Cloud / DevOps Engineer": {
    Linux: 80,
    Docker: 80,
    Kubernetes: 70,
    AWS: 75,
    "CI/CD": 70,
    Python: 60,
  },
};

export const ALL_SKILLS = Array.from(
  new Set(Object.values(CAREER_SKILL_MAP).flatMap((m) => Object.keys(m))),
).sort();

export const ALL_INTERESTS = [
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Web Development",
  "Mobile Development",
  "Cybersecurity",
  "Cloud Computing",
  "Robotics",
  "UI/UX Design",
  "Product Management",
  "Blockchain",
  "IoT",
];

export const DEFAULT_PROFILE: StudentProfile = {
  name: "",
  department: "CSE",
  year: 2,
  location: "Bangalore",
  careerGoal: "Machine Learning Engineer",
  skills: [
    { name: "Python", level: 62 },
    { name: "DSA", level: 74 },
    { name: "SQL", level: 48 },
    { name: "Machine Learning", level: 34 },
    { name: "Statistics", level: 28 },
    { name: "Deep Learning", level: 16 },
  ],
  interests: ["Artificial Intelligence", "Machine Learning", "Data Science"],
  preferredTypes: ["Hackathon", "Competition", "Workshop"],
  travelRadiusKm: 40,
  summary:
    "Second-year CSE student who knows Java and C, is learning Python and wants to become a machine learning engineer.",
};

const day = 24 * 60 * 60 * 1000;
const iso = (offsetDays: number) =>
  new Date(Date.now() + offsetDays * day).toISOString().slice(0, 10);

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "ai-innovation-hackathon",
    title: "AI Innovation Hackathon 2.0",
    organizer: "TechSpark Labs",
    description:
      "A 36-hour hackathon where teams build intelligent autonomous systems using computer vision, LLMs and reinforcement learning. Mentors from applied AI teams review every prototype.",
    type: "Hackathon",
    location: "Bangalore",
    isOnline: false,
    distanceKm: 6,
    startDate: iso(13),
    registrationDeadline: iso(4),
    tags: ["AI", "Computer Vision", "LLM", "Team Event"],
    skills: ["Python", "Machine Learning", "Deep Learning", "DSA"],
    careerTracks: ["Machine Learning Engineer", "Data Analyst"],
    departments: ["CSE", "ISE", "AIML", "ECE"],
    image: "from-violet-500 via-indigo-500 to-blue-500",
    prize: "₹1,50,000 pool",
    seats: 240,
  },
  {
    id: "ml-foundations-workshop",
    title: "Machine Learning Foundations Workshop",
    organizer: "IISc Outreach",
    description:
      "Hands-on weekend workshop covering regression, classification, model evaluation and the statistics you actually need to reason about ML models.",
    type: "Workshop",
    location: "Bangalore",
    isOnline: false,
    distanceKm: 15,
    startDate: iso(8),
    registrationDeadline: iso(3),
    tags: ["ML", "Statistics", "Beginner Friendly"],
    skills: ["Machine Learning", "Statistics", "Python"],
    careerTracks: ["Machine Learning Engineer", "Data Analyst"],
    departments: ["CSE", "ISE", "AIML", "MATH"],
    image: "from-emerald-500 via-teal-500 to-cyan-500",
    seats: 80,
  },
  {
    id: "data-science-championship",
    title: "National Data Science Championship",
    organizer: "AnalyticsIndia",
    description:
      "Online competition on a real retail forecasting dataset. Public leaderboard, weekly baselines and a write-up round judged by practising data scientists.",
    type: "Competition",
    location: "Online",
    isOnline: true,
    distanceKm: 0,
    startDate: iso(20),
    registrationDeadline: iso(11),
    tags: ["Data Science", "Leaderboard", "Forecasting"],
    skills: ["Python", "Machine Learning", "Statistics", "SQL"],
    careerTracks: ["Machine Learning Engineer", "Data Analyst"],
    departments: ["CSE", "ISE", "AIML", "MATH", "ECE"],
    image: "from-amber-500 via-orange-500 to-rose-500",
    prize: "₹80,000 pool",
  },
  {
    id: "deep-learning-bootcamp",
    title: "Deep Learning Bootcamp: CNNs to Transformers",
    organizer: "Neural Academy",
    description:
      "Five evening sessions taking you from convolutional networks to attention and transformers, with a capstone model you deploy at the end.",
    type: "Bootcamp",
    location: "Online",
    isOnline: true,
    distanceKm: 0,
    startDate: iso(26),
    registrationDeadline: iso(17),
    tags: ["Deep Learning", "Transformers", "Capstone"],
    skills: ["Deep Learning", "Python", "Machine Learning"],
    careerTracks: ["Machine Learning Engineer"],
    departments: ["CSE", "ISE", "AIML"],
    image: "from-fuchsia-500 via-purple-500 to-indigo-500",
    seats: 120,
  },
  {
    id: "ml-research-internship",
    title: "Applied ML Research Internship",
    organizer: "Fable AI",
    description:
      "Eight-week paid internship working with an applied research pod on retrieval and ranking models. Open to pre-final year students with Python fundamentals.",
    type: "Internship",
    location: "Bangalore",
    isOnline: false,
    distanceKm: 11,
    startDate: iso(38),
    registrationDeadline: iso(9),
    tags: ["Paid", "Research", "Ranking"],
    skills: ["Python", "Machine Learning", "DSA", "SQL"],
    careerTracks: ["Machine Learning Engineer", "Data Analyst"],
    departments: ["CSE", "ISE", "AIML"],
    image: "from-sky-500 via-blue-500 to-indigo-600",
    prize: "₹25,000 / month",
  },
  {
    id: "sql-analytics-sprint",
    title: "SQL & Analytics Sprint",
    organizer: "DataCircle",
    description:
      "A two-day sprint on window functions, cohort analysis and dashboard storytelling using a live product dataset.",
    type: "Workshop",
    location: "Bangalore",
    isOnline: false,
    distanceKm: 22,
    startDate: iso(6),
    registrationDeadline: iso(2),
    tags: ["SQL", "Dashboards", "Analytics"],
    skills: ["SQL", "Data Visualization", "Statistics"],
    careerTracks: ["Data Analyst", "Machine Learning Engineer"],
    departments: ["CSE", "ISE", "MBA", "MATH"],
    image: "from-lime-500 via-emerald-500 to-teal-500",
    seats: 60,
  },
  {
    id: "fullstack-build-weekend",
    title: "Full Stack Build Weekend",
    organizer: "DevGuild",
    description:
      "Ship a production-ready Next.js and Node application in 48 hours, including auth, database design and deployment.",
    type: "Hackathon",
    location: "Hyderabad",
    isOnline: false,
    distanceKm: 570,
    startDate: iso(17),
    registrationDeadline: iso(8),
    tags: ["Next.js", "Node", "Shipping"],
    skills: ["JavaScript", "React", "Node.js", "SQL"],
    careerTracks: ["Full Stack Developer"],
    departments: ["CSE", "ISE"],
    image: "from-rose-500 via-pink-500 to-fuchsia-500",
  },
  {
    id: "cloud-devops-lab",
    title: "Cloud & DevOps Practitioner Lab",
    organizer: "CloudNative Collective",
    description:
      "Containerise, orchestrate and monitor a microservice stack. Covers Docker, Kubernetes basics and CI/CD pipelines.",
    type: "Workshop",
    location: "Online",
    isOnline: true,
    distanceKm: 0,
    startDate: iso(12),
    registrationDeadline: iso(6),
    tags: ["Docker", "Kubernetes", "CI/CD"],
    skills: ["Docker", "Kubernetes", "Linux", "CI/CD"],
    careerTracks: ["Cloud / DevOps Engineer", "Full Stack Developer"],
    departments: ["CSE", "ISE", "ECE"],
    image: "from-cyan-500 via-sky-500 to-blue-600",
  },
  {
    id: "capture-the-flag",
    title: "Capture The Flag: Campus Edition",
    organizer: "SecureByte",
    description:
      "Beginner to intermediate CTF covering web exploitation, forensics and cryptography challenges over one night.",
    type: "Competition",
    location: "Bangalore",
    isOnline: false,
    distanceKm: 9,
    startDate: iso(10),
    registrationDeadline: iso(5),
    tags: ["Security", "CTF", "Crypto"],
    skills: ["Networking", "Linux", "Cryptography", "Python"],
    careerTracks: ["Cybersecurity Analyst"],
    departments: ["CSE", "ISE", "ECE"],
    image: "from-slate-600 via-gray-700 to-zinc-800",
  },
  {
    id: "product-design-jam",
    title: "Product Design Jam",
    organizer: "Craft Studio",
    description:
      "Design sprint format: research, wireframe and prototype a campus product in Figma with critique from senior designers.",
    type: "Workshop",
    location: "Bangalore",
    isOnline: false,
    distanceKm: 18,
    startDate: iso(15),
    registrationDeadline: iso(7),
    tags: ["Figma", "Design Sprint", "Prototyping"],
    skills: ["UI/UX", "Figma", "User Research"],
    careerTracks: ["Product Designer"],
    departments: ["CSE", "DESIGN", "MBA"],
    image: "from-orange-400 via-amber-500 to-yellow-500",
  },
  {
    id: "robotics-autonomy-challenge",
    title: "Autonomous Robotics Challenge",
    organizer: "RoboWorks",
    description:
      "Build a perception and control stack for a small autonomous rover. Strong overlap with computer vision and reinforcement learning.",
    type: "Competition",
    location: "Chennai",
    isOnline: false,
    distanceKm: 340,
    startDate: iso(29),
    registrationDeadline: iso(14),
    tags: ["Robotics", "Autonomy", "Computer Vision"],
    skills: ["Python", "Machine Learning", "Deep Learning"],
    careerTracks: ["Machine Learning Engineer"],
    departments: ["CSE", "ECE", "MECH", "AIML"],
    image: "from-indigo-500 via-blue-600 to-cyan-600",
    prize: "₹60,000 pool",
  },
  {
    id: "stats-for-ml-seminar",
    title: "Statistics for Machine Learning Seminar",
    organizer: "Department of Mathematics",
    description:
      "Two-hour seminar unpacking distributions, hypothesis testing and bias-variance intuition for ML practitioners.",
    type: "Seminar",
    location: "Bangalore",
    isOnline: false,
    distanceKm: 3,
    startDate: iso(5),
    registrationDeadline: iso(2),
    tags: ["Statistics", "Fundamentals"],
    skills: ["Statistics", "Machine Learning"],
    careerTracks: ["Machine Learning Engineer", "Data Analyst"],
    departments: ["CSE", "ISE", "MATH", "AIML"],
    image: "from-teal-500 via-emerald-600 to-green-600",
  },
  {
    id: "react-performance-workshop",
    title: "React Performance Workshop",
    organizer: "Frontend Guild",
    description:
      "Profiling, memoisation, streaming and server components — measure and fix real performance bottlenecks.",
    type: "Workshop",
    location: "Online",
    isOnline: true,
    distanceKm: 0,
    startDate: iso(9),
    registrationDeadline: iso(4),
    tags: ["React", "Performance"],
    skills: ["React", "JavaScript"],
    careerTracks: ["Full Stack Developer"],
    departments: ["CSE", "ISE"],
    image: "from-blue-500 via-indigo-500 to-violet-600",
  },
  {
    id: "genai-build-sprint",
    title: "GenAI Build Sprint: RAG Systems",
    organizer: "OpenStack Campus",
    description:
      "Build a retrieval augmented generation assistant end to end: embeddings, vector search, evaluation and guardrails.",
    type: "Hackathon",
    location: "Online",
    isOnline: true,
    distanceKm: 0,
    startDate: iso(22),
    registrationDeadline: iso(12),
    tags: ["GenAI", "RAG", "Embeddings"],
    skills: ["Python", "Machine Learning", "Deep Learning", "SQL"],
    careerTracks: ["Machine Learning Engineer", "Full Stack Developer"],
    departments: ["CSE", "ISE", "AIML"],
    image: "from-purple-500 via-violet-500 to-blue-500",
    prize: "₹40,000 pool",
  },
];

export const getOpportunity = (id: string) =>
  OPPORTUNITIES.find((o) => o.id === id);
